In [2]:
#造棋盤
struct ChessBoard
    board::Matrix
end

In [6]:
A = [1 2 3;
    4 5 6]

2×3 Array{Int64,2}:
 1  2  3
 4  5  6

In [7]:
cb = ChessBoard(A)

ChessBoard([1 2 3; 4 5 6])

In [8]:
#呼叫
cb.board

2×3 Array{Int64,2}:
 1  2  3
 4  5  6

In [12]:
cb.board[1,3]

3

In [13]:
#位置
struct Position
x
y
end

In [14]:
p = Position(3,4)

Position(3, 4)

In [16]:
#確認位置能不能放
B = trues(8,8)

8×8 BitArray{2}:
 true  true  true  true  true  true  true  true
 true  true  true  true  true  true  true  true
 true  true  true  true  true  true  true  true
 true  true  true  true  true  true  true  true
 true  true  true  true  true  true  true  true
 true  true  true  true  true  true  true  true
 true  true  true  true  true  true  true  true
 true  true  true  true  true  true  true  true

In [17]:
#可變動的棋盤
mutable struct ChessBoard2
    board::Matrix
end

In [18]:
cb2 = ChessBoard2(A)

ChessBoard2([1 2 3; 4 5 6])

In [19]:
cb2.board = B

8×8 BitArray{2}:
 true  true  true  true  true  true  true  true
 true  true  true  true  true  true  true  true
 true  true  true  true  true  true  true  true
 true  true  true  true  true  true  true  true
 true  true  true  true  true  true  true  true
 true  true  true  true  true  true  true  true
 true  true  true  true  true  true  true  true
 true  true  true  true  true  true  true  true

In [20]:
#宣告我要幾x幾的棋盤
struct ChessBoard
    board::Matrix
    ChessBoard(m,n) = new(trues(m,n))
end

In [21]:
cb = ChessBoard(8,8) #8,8丟到後面的trues

ChessBoard(Bool[true true … true true; true true … true true; … ; true true … true true; true true … true true])

In [23]:
cb.board

8×8 Array{Bool,2}:
 true  true  true  true  true  true  true  true
 true  true  true  true  true  true  true  true
 true  true  true  true  true  true  true  true
 true  true  true  true  true  true  true  true
 true  true  true  true  true  true  true  true
 true  true  true  true  true  true  true  true
 true  true  true  true  true  true  true  true
 true  true  true  true  true  true  true  true

In [28]:
Matrix{Int64}(8,8)

8×8 Array{Int64,2}:
 4626268480           0           0  …           0  4626268608  4626268224
 4908161840           0           0              0  4626268800  4908067376
          0           0  4626268416              0           0  4884574464
          0           0  4908157264              0           0  4907787344
 4626268736  4626268864  4626269120     4626251792           0           0
 4908062736  4907786384  4908070224  …           0           0           0
          0  4626268800  4626268992     4626268352           0           0
          0  4908062800  4908070064     4907786960           0           0

In [32]:
#宣告要什麼類別
struct ChessBoard3{T}
    board::Matrix{T}
    ChessBoard3{T}(m,n) where T = new(zeros(T,m,n))
end

In [33]:
cb3 = ChessBoard3{Bool}(8, 8)

ChessBoard3{Bool}(Bool[false false … false false; false false … false false; … ; false false … false false; false false … false false])

In [34]:
struct ChessBoard4
    board::Matrix{Bool}
    ChessBoard4(n) = new(trues(n, n))
end

In [35]:
check(cb::ChessBoard4, x, y) = cb.board[x, y]

check (generic function with 1 method)

In [36]:
function place!(cb::ChessBoard4, x, y)
    cb.board[x, :] = false #橫的都填false
    cb.board[:, y] = false #直的都填false
    cb
end

place! (generic function with 1 method)

In [37]:
cb = ChessBoard4(8)

ChessBoard4(Bool[true true … true true; true true … true true; … ; true true … true true; true true … true true])

In [38]:
place!(cb,3,4) #位置放在(3,4)

ChessBoard4(Bool[true true … true true; true true … true true; … ; true true … true true; true true … true true])

In [39]:
cb.board

8×8 Array{Bool,2}:
  true   true   true  false   true   true   true   true
  true   true   true  false   true   true   true   true
 false  false  false  false  false  false  false  false
  true   true   true  false   true   true   true   true
  true   true   true  false   true   true   true   true
  true   true   true  false   true   true   true   true
  true   true   true  false   true   true   true   true
  true   true   true  false   true   true   true   true

In [40]:
function place!(cb::ChessBoard4, x, y)  # v2
    cb.board[x, :] = false
    cb.board[:, y] = false
    for i in 1:8
        #撞到邊界用取餘數來解
        x1 = ((x+i) % 8 == 0)? 8 : (x+i) % 8
        y1 = ((y+i) % 8 == 0)? 8 : (y+i) % 8
        cb.board[x1, y1] = false
        x2 = ((x-i+8) % 8 == 0)? 8 : (x-i+8) % 8
        y2 = ((y+i) % 8 == 0)? 8 : (y+i) % 8
        cb.board[x2, y2] = false
    end
    cb 
end

place! (generic function with 1 method)

In [41]:
#出現問題：邊界跳下一行
cb = ChessBoard4(8)
place!(cb, 3, 4)
cb.board

8×8 Array{Bool,2}:
  true  false   true  false   true  false   true   true
  true   true  false  false  false   true   true   true
 false  false  false  false  false  false  false  false
  true   true  false  false  false   true   true   true
  true  false   true  false   true  false   true   true
 false   true   true  false   true   true  false   true
  true   true   true  false   true   true   true  false
 false   true   true  false   true   true  false   true

In [43]:
get_position(x) = ((x+8) % 8 == 0)? 8 : (x+8) % 8
function filter_accessory_positions(pos)
    skip = false
    results = Tuple[]
    for (x, y) in pos
        if !skip
            push!(results, (x, y))
        end
        if x == 8
            skip = ~skip
        end
        if y == 8
            skip = ~skip
        end
    end
    return results
end

filter_accessory_positions (generic function with 1 method)

In [44]:
function place!(cb::ChessBoard4, x, y)  # v3
    cb.board[x, :] = false
    cb.board[:, y] = false
    pos = [(get_position(x+i), get_position(y+i)) for i in 1:8]
    pos = filter_accessory_positions(pos)
    for (x, y) in pos
        cb.board[x, y] = false
    end
    pos = [(get_position(x-i), get_position(y+i)) for i in 1:8]
    pos = filter_accessory_positions(pos)
    for (x, y) in pos
        cb.board[x, y] = false
    end
    cb 
end

place! (generic function with 1 method)

In [45]:
cb = ChessBoard4(8)
place!(cb, 3, 4)
cb.board

8×8 Array{Bool,2}:
  true  false   true  false   true  false   true   true
  true   true  false  false  false   true   true   true
 false  false  false  false  false  false  false  false
  true   true  false  false  false   true   true   true
  true  false   true  false   true  false   true   true
 false   true   true  false   true   true  false   true
  true   true   true  false   true   true   true  false
  true   true   true  false   true   true  false   true

In [46]:
#Abstruct type
abstract type Animal end
struct Dog <: Animal
    name::String
end
struct Cat <: Animal
    name::String
end

In [47]:
name(a::Animal) = println("My name is $(a.name)")

name (generic function with 1 method)

In [48]:
小黃 = Dog("小黃")

Dog("小黃")

In [49]:
name(小黃)

My name is 小黃


In [50]:
#定義的類別
supertype(Dog)

Animal

In [53]:
supertype(Animal)

Any